# tmux.conf
set -ag terminal-overrides ",xterm-256color:RGB"
set-option -g status-position top
set -g status-style bg=default

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g status-interval 5
set -g automatic-rename on
set -g automatic-rename-format '#{b:pane_current_path}'